import { media, renderJobs, videoProjects } from "@/server/db/schema";

export interface MediaVersion {
  id: string;
  type: string;
  url: string;
  key: string;
  prompt: string | null;
  modelUsed: string | null;
  createdAt: string;
}

export interface FrameVariant {
  id: string;
  type: string;
  url: string;
  prompt: string | null;
  modelUsed: string;
  createdAt: string;
}

export interface SceneFrame {
  id: string;
  frameOrder: number;
  clipDuration: number | null;
  imagePrompt: string | null;
  /** Merged ImageSpec persisted after prompt generation (optional on older rows). */
  imageSpec?: Record<string, unknown> | null;
  /** Last contract assessment metadata (optional on older rows). */
  promptContractMeta?: Record<string, unknown> | null;
  /** Structured motion fields when generated by the motion director; cleared if user edits motion text. */
  motionSpec?: {
    primaryAction: string;
    cameraMove: string;
    subjectDynamics: string;
    endState: string;
    negativeMotion: string;
    endFramePolicy?: "anchor" | "freeform";
  } | null;
  visualDescription: string | null;
  imageUrl: string | null;
  videoUrl: string | null;
  media?: FrameVariant[];
  motionGeneratedAt?: string | null;
  imageMediaId?: string | null;
  videoMediaId?: string | null;
}

export interface Scene {
  id: string;
  sceneOrder: number;
  sceneTitle: string | null;
  directorNote: string | null;
  text: string;
  imagePrompt: string | null;
  visualDescription: string | null;
  searchQuery: string | null;
  speaker: string | null;
  duration: number;
  assetUrl: string | null;
  assetType: string | null;
  audioUrl: string | null;
  assetRefs: string[] | null;
  media?: MediaVersion[];
  frames?: SceneFrame[];
}

export interface StoryAssetItem {
  id: string;
  type: "character" | "location" | "prop";
  name: string;
  description: string;
  url: string;
  sheetUrl?: string;
  voiceId?: string;
}

export type RenderJob = typeof renderJobs.$inferSelect;

export type VideoDetail = typeof videoProjects.$inferSelect & { renderJobs?: RenderJob[] };

export type Media = typeof media.$inferSelect & { modelUsed: TVideoModelId | TImageModelId };

export interface ChatMsg {
  role: "user" | "assistant";
  content: string;
}

export interface RefinedScene {
  sceneOrder: number;
  sceneTitle?: string;
  directorNote?: string;
  text: string;
  imagePrompt: string;
  visualDescription: string;
  searchQuery: string;
  duration: number;
}

export interface FieldChange {
  field: string;
  old?: string;
  new?: string;
}

export interface SceneChange {
  scene: number;
  type: "modified" | "added" | "removed";
  fields: FieldChange[];
}

export interface SceneUpdates {
  text?: string;
  duration?: number;
  speaker?: string;
  visualDescription?: string;
  sceneTitle?: string;
  directorNote?: string;
}
